enabled_events:
  HeaderEvent: true
  TransactionsEvent: true
  LogsEvent: true
  BuilderBidsEvent: true
  ProposerPayloadsEvent: true
  OmmersEvent: true
  WithdrawalsEvent: true
  Erc20TransfersEvent: true